version: '3'
services:
    randevumapi:
        image: snrtbnc/randevumapi
        ports: 
            - '5000:5000'
        depends_on:
                    - mongo
    randevumui:
        stdin_open: true
        image: snrtbnc/randevumui
        ports: 
            - '3000:3000'
        environment:
            APIURL : ${APIURL}
    mongo:
        image: mongo
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - './data:/data/db'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MongoUserName}
            MONGO_INITDB_ROOT_PASSWORD: ${MongoPassWord}
        